name: legacy package file
run-name: ${{ github.actor }} is checking out files
on: 
  push:
    branches:
      - main
jobs:
  install-package:
    runs-on: windows-latest
    steps:
      - name: install
        uses: actions/checkout@v3
        run: npm install
  build-package:
    runs-on: windows-latest
    steps:
      - name: build
        uses: actions/checkout@v3
        run: npm build
  test-functions:
    runs-on: windows-latest
    steps:
      - name: test
        uses: actions/checkout@v3
        run: npm test
  publish-package:
    runs-on: windows-latest
    steps:
      - name: publish
        uses: actions/checkout@v3
        run: npm publish_package   

    