name: legacy package file
run-name: ${{ github.actor }} is checking out files
on: 
  push:
  pull_request:
    branches:
        - main
    types: [opened, reopened]
jobs:
  puplish-package:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/

      - name: install
        run: npm install
   
      - name: build
        run: npm run build

      - name: test
        run: npm run test
        if: ${{ github.ref == 'refs/head/main'}}
      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    