name: legacy package file
run-name: ${{ github.actor }} is checking out files
on: 
  push:
    branches:
      - main
jobs:
  install-package:
    runs-on: windows-latest
    steps:
      - name: install
      - run: npm install
  build-package:
    runs-on: windows-latest
    steps:
      - name: build
      - run: npm build
  test-functions:
    runs-on: windows-latest
    steps:
      - name: test
      - run: npm test
  publish-package:
    runs-on: windows-latest
    steps:
      - name: publish
      - run: npm publish_package   

    