name: legacy package file
run-name: ${{ github.actor }} is checking out files
on: 
  push:
    branches:
      - main
jobs:
  puplish-package:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install
        run: npm install
   
      - name: build
        run: npm run build

      - name: test
        run: npm run test

      - name: publish
        run: npm run publish_npm  

    